// hify-client/src/views/AlbumsPage.vue
<script setup lang="ts">
import AlbumCard from '@/components/molecules/AlbumCard.vue';
import { logFatal } from '@/global/stores/debugger';
import { gqlClient } from '@/global/urql-client';
import { graphql } from '@/graphql/generated';
import type { AlbumFragment, AlbumsPageQuery } from '@/graphql/generated/graphql';
import Grid from '@/navigable/ui/organisms/Grid.vue';
import { onMounted, ref } from 'vue';

const ALBUMS_PER_LINE = 6
const LINES_PER_PAGE = 5

async function feedMore() {
  if (currentPageInfo.value?.hasNextPage === false) {
    return
  }

  const { data, error } = await gqlClient.query(
    graphql(`
      query AlbumsPage($pagination: PaginationInput!) {
        albums(pagination: $pagination) {
          nodes {
            ...Album
          }

          pageInfo {
            endCursor
            hasNextPage
          }
        }
      }
    `),
    {
      pagination: {
        after: currentPageInfo.value?.endCursor,
        first: ALBUMS_PER_LINE * LINES_PER_PAGE
      }
    }
  )

  if (!data) {
    logFatal('Failed to fetch albums list', error)
  }

  currentPageInfo.value = data.albums.pageInfo
  albums.value.push(...data.albums.nodes)
}

const currentPageInfo = ref<AlbumsPageQuery['albums']['pageInfo'] | null>(null)

const albums = ref<AlbumFragment[]>([])

onMounted(feedMore)
</script>

<template>
  <Grid :columns="ALBUMS_PER_LINE" :lazy-loader="feedMore">
    <AlbumCard v-for="album in albums" :key="album.id" :album />
  </Grid>
</template>

// hify-client/src/pages/AlbumsPage/AlbumsPage.svelte
<script lang="ts">
  import { AlbumCardFragment, AsyncAlbumsPage } from '../../graphql/generated'

  import Grid from '../../navigable/ui/organisms/Grid/Grid.svelte'
  import AlbumCard from '../../molecules/AlbumCard/AlbumCard.svelte'

  const ALBUMS_PER_LINE = 6
  const LINES_PER_PAGE = 5

  let currentPageInfo: { endCursor?: string | null; hasNextPage: boolean } | null = null

  const feedMore = async () => {
    if (currentPageInfo?.hasNextPage === false) {
      return
    }

    const res = await AsyncAlbumsPage({
      variables: {
        pagination: {
          after: currentPageInfo?.endCursor,
          first: ALBUMS_PER_LINE * LINES_PER_PAGE,
        },
      },
    })

    currentPageInfo = res.data.albums.pageInfo
    albums = [...albums, ...res.data.albums.nodes]
  }

  let albums: AlbumCardFragment[] = []
</script>

{#await feedMore()}
  <h2>Loading...</h2>
{:then _}
  <Grid columns={ALBUMS_PER_LINE} lazyLoader={feedMore}>
    {#each albums as album}
      <AlbumCard {album} />
    {/each}
  </Grid>
{:catch e}
  <h2>Failed: {e.message}</h2>
{/await}
