// hify-client/src/components/molecules/InteractiveCard.vue
<script setup lang="ts">
import type { ArtFragment } from '@/graphql/generated/graphql'
import type { SimpleNavigableItemProps } from '@/navigable/headless/SimpleNavigableItem/SimpleNavigableItem.vue'
import SimpleNavigableItem from '@/navigable/headless/SimpleNavigableItem/SimpleNavigableItem.vue';
import Card from './Card.vue';

// TODO: inherit some props from 'Card' and from 'SimpleNavigableItem'
defineProps<{
    art: ArtFragment | null | undefined,
    title: string,

    subtitle?: string,
    onPress: SimpleNavigableItemProps['onPress'],

    onLongPress?: SimpleNavigableItemProps['onLongPress'],
    onFocus?: SimpleNavigableItemProps['onFocus'],

    enforceMaxWidth?: boolean,
    circle?: boolean
}>()
</script>

<template>
    <SimpleNavigableItem :on-press :on-long-press :on-focus>
        <Card :art :title :subtitle :enforce-max-width :circle />
    </SimpleNavigableItem>
</template>

// hify-client/src/molecules/Card/InteractiveCard.svelte
<script lang="ts">
  import { ProgressiveImgFragment } from '../../graphql/generated'
  import SimpleNavigableItem from '../../navigable/headless/SimpleNavigableItem/SimpleNavigableItem.svelte'
  import Card from './Card.svelte'

  export let art: ProgressiveImgFragment | null | undefined

  export let title: string
  export let subtitle: string | null = null

  export let onPress: () => void
  export let onLongPress: (() => void) | undefined = undefined

  export let enforceMaxWidth: boolean | undefined = undefined
  export let circle: boolean | undefined = undefined
</script>

<SimpleNavigableItem {onPress} {onLongPress}>
  <Card {art} {title} {subtitle} {enforceMaxWidth} {circle} />
</SimpleNavigableItem>
