// hify-client/src/molecules/ContextMenu/ContextMenu.svelte
<script context="module" lang="ts">
  export type ContextMenuOption = {
    label: string
    onPress: () => void
    // onLongPress?: () => void
  }

  export type ContextMenuStore = Writable<{ options: ContextMenuOption[] } | null>

  export function createContextMenu(): ContextMenuStore {
    return writable(null)
  }

  export function showContextMenu(store: ContextMenuStore, options: ContextMenuOption[]): void {
    store.set({ options })
  }
</script>

<script lang="ts">
  import { afterUpdate } from 'svelte'
  import { Writable, writable } from 'svelte/store'

  import { getParentNavigable, NavigableItem, RequestFocus } from '../../navigable/navigation'

  import NavigableWithHandlers from '../../navigable/NavigableWithHandlers/NavigableWithHandlers.svelte'
  import SimpleNavigableItem from '../../navigable/SimpleNavigableItem/SimpleNavigableItem.svelte'
  import { logFatal } from '../../stores/debugger'
  import ItemStyleLayer from '../../navigable/SimpleNavigableItem/ItemStyleLayer.svelte'
  import Column from '../../atoms/Column/Column.svelte'

  const nav = getParentNavigable()

  export let store: ContextMenuStore

  let ctxTop = -1
  let ctxLeft = -1
  let prevItem: NavigableItem | null = null

  function getBoundingClientRect(el: HTMLElement): DOMRect | null {
    let rect = el.getBoundingClientRect()
    const children = [...el.children]

    while (
      rect.top === 0 &&
      rect.left === 0 &&
      rect.right === 0 &&
      rect.bottom === 0 &&
      rect.height === 0 &&
      rect.width === 0
    ) {
      const child = children.shift()

      if (!child) {
        return null
      }

      rect = child.getBoundingClientRect()
    }

    return rect
  }

  afterUpdate(() => {
    if (!$store || !$store.options.length) {
      return
    }

    const focusedItem = nav.page.focusedItem()

    if (!focusedItem) {
      return
    }

    if (!requestFocus) {
      return logFatal('Focus request binding is not defined in ContextMenu component')
    }

    const rect = getBoundingClientRect(focusedItem.underlyingElement())

    ctxTop = rect ? (rect.top + rect.bottom) / 2 : 0
    ctxLeft = rect ? (rect.left + rect.right) / 2 : 0

    prevItem = focusedItem
    requestFocus()
    return
  })

  export function hideContextMenu(): void {
    store.set(null)
    prevItem?.requestFocus()
  }

  let requestFocus: RequestFocus
</script>

{#if $store && $store.options.length > 0}
  <NavigableWithHandlers onBack={hideContextMenu}>
    <div class="container" style="--ctx-top: {ctxTop}px; --ctx-left: {ctxLeft}px;">
      <Column bind:requestFocus>
        {#each $store.options as { label, onPress }}
          <SimpleNavigableItem
            onPress={() => {
              hideContextMenu()
              onPress()
            }}
          >
            <ItemStyleLayer>
              <div class="option">{label}</div>
            </ItemStyleLayer>
          </SimpleNavigableItem>
        {/each}
      </Column>
    </div>
  </NavigableWithHandlers>
{/if}

<style>
  .container {
    position: fixed;
    top: var(--ctx-top);
    left: var(--ctx-left);
    display: inline-block;
    background-color: lightgray;
    color: black;
    border: 1px solid black;
    z-index: 10;
  }

  .option {
    padding: 5px;
  }

  .option:not(:last-child) {
    border-bottom: 1px solid black;
  }
</style>

// hify-client/src/navigable/ui/molecules/ContextMenu/ContextMenu.vue
<script setup lang="ts">
import type { NavigableItem } from '@/navigable/navigation'
import NavigableWithHandlers from '@/navigable/headless/NavigableWithHandlers/NavigableWithHandlers.vue'
import SimpleNavigableItem from '@/navigable/headless/SimpleNavigableItem/SimpleNavigableItem.vue'
import Column from '../Column/Column.vue'
import { contextMenuStore } from './ContextMenu'
import { logFatal } from '@/global/stores/debugger'
import { onUpdated, ref } from 'vue'
import Run from '@/components/atoms/Run.vue'
import type { NavigableList } from '@/navigable/headless/NavigableList/NavigableList'

function getBoundingClientRect(el: HTMLElement): DOMRect | null {
  let rect = el.getBoundingClientRect()
  const children = Array.from(el.children)

  while (
    rect.top === 0 &&
    rect.left === 0 &&
    rect.right === 0 &&
    rect.bottom === 0 &&
    rect.height === 0 &&
    rect.width === 0
  ) {
    const child = children.shift()

    if (!child) {
      return null
    }

    rect = child.getBoundingClientRect()
  }

  return rect
}

onUpdated(() => {
  if (!containerRef.value) {
    return
  }

  const container = containerRef.value
  const column = columnRef.value ?? logFatal('Column reference not initialized yet')

  const focusedItem = column.page.focusedItem()
  if (!contextMenuStore.value || !contextMenuStore.value.options.length || !focusedItem) {
    return
  }

  const rect = getBoundingClientRect(focusedItem.underlyingElement())

  const top = rect ? (rect.top + rect.bottom) / 2 : 0
  const left = rect ? (rect.left + rect.right) / 2 : 0

  ctxTop.value = top + container.clientHeight > window.innerHeight ? window.innerHeight - container.clientHeight - 5 : top
  ctxLeft.value = left + container.clientWidth > window.innerWidth ? window.innerWidth - container.clientWidth - 5 : left

  prevFocusItem.value = focusedItem

  column.requestFocus()
})

function closeContextMenu() {
  prevFocusItem.value?.requestFocus()
  contextMenuStore.value = null
}

const prevFocusItem = ref<NavigableItem<unknown> | null>(null)

const ctxTop = ref(-1)
const ctxLeft = ref(-1)

const columnRef = ref<NavigableList | null>(null)
const containerRef = ref<HTMLDivElement | null>(null)
</script>

<template>
  <NavigableWithHandlers v-if="contextMenuStore && contextMenuStore.options.length > 0" @back="closeContextMenu">
    <div class="container" ref="containerRef" :style="`top: ${ctxTop}px; left: ${ctxLeft}px;`">
      <Column trapped v-slot="{ column }">
        <Run :run="() => columnRef = column" />

        <SimpleNavigableItem v-for="option in contextMenuStore.options" :key="option.label"
          @press="closeContextMenu(); option.onPress()" v-slot="{ focused }">
          <div class="option-container" :class="{ focused }">
            <div class="option">{{ option.label }}</div>
          </div>
        </SimpleNavigableItem>
      </Column>
    </div>
  </NavigableWithHandlers>
</template>

<style scoped>
.container {
  position: fixed;

  background-color: rgb(42, 42, 42);
  color: white;

  border: 1px solid rgb(78, 78, 78);
  border-radius: 5px;

  box-shadow: 2px 2px 5px rgb(60, 60, 60);

  z-index: 10;
}

.option-container.focused {
  background-color: darkgray;
}

.option {
  padding: 5px;
}

.option:not(:last-child) {
  border-bottom: 1px solid black;
}
</style>
