// hify-client/src/navigable/NavigableRow/NavigableRow.svelte
<script lang="ts">
  import { onDestroy } from 'svelte'

  import { getParentNavigable, setChildrenNavigable } from '../navigation'
  import { NavigableRow } from './NavigableRow'

  const nav = getParentNavigable()
  const row = new NavigableRow(nav)

  nav.append(row)

  setChildrenNavigable(row)

  onDestroy(() => nav.remove(row))
</script>

<slot nav={row} />

// hify-client/src/navigable/headless/NavigableRow/NavigableRow.vue
<script setup lang="ts">
import { type NavigableCommonProps, getParentNavigable } from '@/navigable/navigation'
import { NavigableRow, type NavigableRowProps } from './NavigableRow'
import InternalNavWrapper from '../InternalNavWrapper.vue'

const props = defineProps<NavigableCommonProps & NavigableRowProps>()

const row = new NavigableRow(getParentNavigable(), props)

defineExpose({ row })

defineSlots<{
	default(props: { row: NavigableRow }): unknown
}>()
</script>

<template>
	<InternalNavWrapper :nav="row" :props>
		<slot :row />
	</InternalNavWrapper>
</template>
