// hify-client/src/navigable/headless/NavigableRow/NavigableRow.svelte
<script lang="ts">
  import { afterUpdate } from 'svelte'

  import { getParentNavigable, Props, setChildrenNavigable } from '../../navigation'
  import InternalNavWrapper from '../InternalNavWrapper.svelte'
  import { NavigableRow } from './NavigableRow'

  export let hasFocusPriority: Props<NavigableRow>['hasFocusPriority'] = null
  export let onFocusChangeCallback: Props<NavigableRow>['onFocusChangeCallback'] | null = null

  const rowProps = (): Props<NavigableRow> => ({
    hasFocusPriority,
    onFocusChangeCallback,
  })

  const row = new NavigableRow(getParentNavigable(), rowProps())

  setChildrenNavigable(row)

  afterUpdate(() => row.updateProps(rowProps()))

  export const requestFocus = () => row.requestFocus()
</script>

<InternalNavWrapper navId={row.id}>
  <slot nav={row} />
</InternalNavWrapper>

// hify-client/src/navigable/headless/NavigableRow/NavigableRow.vue
<script setup lang="ts">
import { type NavigableCommonProps, getParentNavigable } from '@/navigable/navigation'
import { NavigableRow, type NavigableRowProps } from './NavigableRow'
import InternalNavWrapper from '../InternalNavWrapper.vue'

const props = defineProps<NavigableCommonProps & NavigableRowProps>()

const row = new NavigableRow(getParentNavigable(), props)

defineExpose({ row })

defineSlots<{
	default(props: { row: NavigableRow }): unknown
}>()
</script>

<template>
	<InternalNavWrapper :nav="row" :props>
		<slot :row />
	</InternalNavWrapper>
</template>
