// hify-client/src/navigable/headless/SimpleNavigableItem/SimpleNavigableItem.vue
<script lang="ts">
export type SimpleNavigableItemProps = Omit<SimpleNavigableItemClassProps, 'getUnderlyingElement'> & NavigableCommonProps & {
    justForStyle?: boolean
    disabled?: boolean
    fullHeight?: boolean
    unstyled?: boolean
}
</script>

<script setup lang="ts">
import { SimpleNavigableItem, type SimpleNavigableItemProps as SimpleNavigableItemClassProps } from './SimpleNavigableItem';
import { JUST_FOR_STYLE_ITEM_ID, getParentNavigable, type HTMLNavigableItemWrapperElement, type NavigableCommonProps } from '../../navigation'
import { computed, onBeforeUpdate, ref } from 'vue';
import { logFatal } from '@/global/stores/debugger';

const props = defineProps<SimpleNavigableItemProps>()

defineSlots<{
    default(props: { item: SimpleNavigableItem, focused: boolean }): unknown
}>()

const itemProps = computed(() => ({
    ...props,

    onFocus() {
        focused.value = true
        props.onFocus?.()
    },

    onUnfocus() {
        focused.value = false
        props.onUnfocus?.()
    },

    getUnderlyingElement: () =>
        wrapperRef?.value ?? logFatal('Wrapper reference not initialized yet')

}))

const item = new SimpleNavigableItem(getParentNavigable(true), itemProps.value)

onBeforeUpdate(() => item.updateProps(itemProps.value))

defineExpose({
    requestFocus: () => item.requestFocus()
})

const wrapperRef = ref<HTMLNavigableItemWrapperElement | null>(null)
const focused = ref(false)
</script>

<template>
    <navigable-item-wrapper ref="wrapperRef" :class="{ focused, fullHeight, unstyled }"
        :data-navigable-item-id="props.justForStyle ? JUST_FOR_STYLE_ITEM_ID : item.id" @click="props.onPress?.()"
        @contextmenu.prevent="props.onLongPress?.()" @mouseenter="item.requestFocus()"
        @mouseleave="item.page.unfocus()">
        <slot :item :focused />
    </navigable-item-wrapper>
</template>

<style scoped>
navigable-item-wrapper.fullHeight {
    /* -12px for the 2x 6px padding */
    height: calc(100% - 12px);
}
</style>

// hify-client/src/navigable/headless/SimpleNavigableItem/SimpleNavigableItem.svelte
<script context="module" lang="ts">
  export type ItemDisplay = 'inline-block' | 'block' | 'transparent' | null
</script>

<script lang="ts">
  import { SimpleNavigableItem } from './SimpleNavigableItem'
  import {
    getParentNavigable,
    HTMLNavigableItemWrapperElement,
    JUST_FOR_STYLE_ITEM_ID,
    Props,
  } from '../../navigation'
  import { afterUpdate } from 'svelte'

  export let fullHeight = false
  export let noPadding = false
  export let display: ItemDisplay = null
  export let marginRight = 0
  export let notRounded = false
  export let unstyled = false
  export let customStyle = ''

  export let justForStyle = false

  export let hasFocusPriority: Props<SimpleNavigableItem>['hasFocusPriority'] = null

  export let disabled: Props<SimpleNavigableItem>['disabled'] = undefined

  export let onFocus: Props<SimpleNavigableItem>['onFocus'] = undefined
  export let onUnfocus: Props<SimpleNavigableItem>['onUnfocus'] = undefined

  export let onPress: Props<SimpleNavigableItem>['onPress'] = undefined
  export let onLongPress: Props<SimpleNavigableItem>['onLongPress'] = undefined
  export let onBack: Props<SimpleNavigableItem>['onBack'] = undefined

  export let onUp: Props<SimpleNavigableItem>['onUp'] = undefined
  export let onLeft: Props<SimpleNavigableItem>['onLeft'] = undefined
  export let onRight: Props<SimpleNavigableItem>['onRight'] = undefined
  export let onDown: Props<SimpleNavigableItem>['onDown'] = undefined

  const itemProps = (): Props<SimpleNavigableItem> => ({
    hasFocusPriority,

    disabled,

    onFocus: () => {
      focused = true
      onFocus?.()
    },

    onUnfocus: () => {
      focused = false
      onUnfocus?.()
    },

    onPress,
    onLongPress,
    onBack,

    onUp,
    onLeft,
    onRight,
    onDown,

    getUnderlyingElement: () => wrapper,
  })

  const item = new SimpleNavigableItem(getParentNavigable(true), itemProps())

  afterUpdate(() => item.updateProps(itemProps()))

  export const requestFocus = () => item.requestFocus()

  let wrapper: HTMLNavigableItemWrapperElement
  let focused: boolean

  $: translatedDisplay = display === 'transparent' ? 'contents' : display ?? 'inline-block'
</script>

<!-- svelte-ignore a11y-click-events-have-key-events -->
<!-- svelte-ignore a11y-no-static-element-interactions -->
<navigable-item-wrapper
  data-navigable-item-id={!justForStyle ? item.id : JUST_FOR_STYLE_ITEM_ID}
  bind:this={wrapper}
  on:click={() => onPress?.()}
  on:contextmenu|preventDefault={() => onLongPress?.()}
  on:mouseenter={() => item.requestFocus()}
  on:mouseleave={() => item.page.unfocus()}
  class:focused
  class:fullHeight
  class:noPadding
  class:notRounded
  class:unstyled
  style="display: {translatedDisplay}; margin-right: {marginRight}px; {customStyle}"
>
  <slot {item} requestFocus={() => item.requestFocus()} {focused} />
</navigable-item-wrapper>

<style>
  :global(navigable-item-wrapper:not(.noPadding) > :first-child) {
    padding: 5px;
  }

  navigable-item-wrapper.fullHeight {
    /* -10px for the 2x 5px padding */
    height: calc(100% - 10px);
  }

  navigable-item-wrapper.fullHeight.noPadding {
    height: 100%;
  }

  :global(navigable-item-wrapper.fullHeight > :first-child) {
    min-height: 100%;
  }
</style>
