// hify-client/src/navigable/ui/molecules/Row/Row.vue
<script setup lang="ts">
import NavigableRow from '@/navigable/headless/NavigableRow/NavigableRow.vue'
import type { NavigableRowProps } from '@/navigable/headless/NavigableRow/NavigableRow'

const props = defineProps<NavigableRowProps>()
</script>

<template>
  <div class="row">
    <NavigableRow v-bind="props">
      <slot />
    </NavigableRow>
  </div>
</template>

<style scoped>
.row {
  overflow-x: hidden;
  display: flex;
  flex-direction: row;
}
</style>

// hify-client/src/navigable/ui/molecules/Row/Row.svelte
<script lang="ts">
import NavigableRow from '@navigable/headless/NavigableRow/NavigableRow.svelte'
import type { NavigableRowProps } from '../../../headless/NavigableRow/NavigableRow'

export let trapped: NavigableRowProps['trapped'] = undefined
</script>

<div class="row">
  <NavigableRow {trapped}>
    <slot />
  </NavigableRow>
</div>

<style>
  .row {
    overflow-x: hidden;
    display: flex;
    flex-direction: row;
  }
</style>
