// hify-client/src/navigable/ui/molecules/Column/Column.svelte
<script lang="ts">
import type { NavigableList as NavigableListClass } from '../../../headless/NavigableList/NavigableList'
import NavigableList from '../../../headless/NavigableList/NavigableList.svelte'
import type { Props } from '../../../navigation'

export let hasFocusPriority: Props<NavigableListClass>['hasFocusPriority'] = null
export let trapped: Props<NavigableListClass>['trapped'] = undefined
</script>

<div class="column">
  <NavigableList let:requestFocus {hasFocusPriority} {trapped}>
    <slot {requestFocus} />
  </NavigableList>
</div>

<style>
  .column {
    display: flex;
    flex-direction: column;
    overflow-x: auto;
  }
</style>

// hify-client/src/navigable/ui/molecules/Column/Column.vue
<script setup lang="ts">
import type { NavigableList as NavigableListClass, NavigableListProps } from '@/navigable/headless/NavigableList/NavigableList'
import NavigableList from '@/navigable/headless/NavigableList/NavigableList.vue'

defineProps<NavigableListProps>()

defineSlots<{
  default(props: { column: NavigableListClass }): unknown
}>()
</script>

<template>
  <div class="flex flex-col overflow-x-auto">
    <NavigableList v-slot="{ list }">
      <slot :column="list" />
    </NavigableList>
  </div>
</template>
