// hify-client/src/navigable/NavigableWithHandlers/NavigableWithHandlers.svelte
<script lang="ts">
  import { onDestroy } from 'svelte'

  import { getParentNavigable, setChildrenNavigable } from '../navigation'
  import { NavigableWithHandlers, NavigableWithHandlersProps } from './NavigableWithHandlers'

  export let position: NavigableWithHandlersProps['position'] = null

  export let onPress: NavigableWithHandlersProps['onPress'] = undefined
  export let onLongPress: NavigableWithHandlersProps['onLongPress'] = undefined
  export let onBack: NavigableWithHandlersProps['onBack'] = undefined

  const nav = getParentNavigable()
  const row = new NavigableWithHandlers(nav, { position, onPress, onLongPress, onBack })

  nav.append(row)

  setChildrenNavigable(row)

  onDestroy(() => nav.remove(row))
</script>

<slot nav={row} />

// hify-client/src/navigable/headless/NavigableWithHandlers/NavigableWithHandlers.vue
<script setup lang="ts">
import { getParentNavigable } from '@/navigable/navigation'
import InternalNavWrapper from '../InternalNavWrapper.vue'
import { NavigableWithHandlers, type NavigableWithHandlersProps } from './NavigableWithHandlers';

const props = defineProps<NavigableWithHandlersProps>()

const nav = new NavigableWithHandlers(getParentNavigable(), props)

defineExpose({ nav })

defineSlots<{
	default(props: { nav: NavigableWithHandlers }): unknown
}>()
</script>

<template>
	<InternalNavWrapper :nav :props v-bind="$attrs">
		<slot :nav />
	</InternalNavWrapper>
</template>
