// hify-client/src/navigable/NavigableList/NavigableList.svelte
<script lang="ts">
  import { onDestroy } from 'svelte'

  import { getParentNavigable, setChildrenNavigable } from '../navigation'
  import { NavigableList } from './NavigableList'

  const nav = getParentNavigable()
  const list = new NavigableList(nav)

  nav.append(list)

  setChildrenNavigable(list)

  onDestroy(() => nav.remove(list))
</script>

<slot />

// hify-client/src/navigable/headless/NavigableList/NavigableList.vue
<script setup lang="ts">
import { getParentNavigable } from '@/navigable/navigation';
import { NavigableList, type NavigableListProps } from './NavigableList';
import InternalNavWrapper from '../InternalNavWrapper.vue';

const props = defineProps<NavigableListProps>()

const list = new NavigableList(getParentNavigable(), props)

defineExpose({ list })

defineSlots<{
	default(props: { list: NavigableList }): unknown
}>()
</script>

<template>
	<InternalNavWrapper :nav="list" :props>
		<slot :list />
	</InternalNavWrapper>
</template>
