// hify-client/src/navigable/headless/NavigableList/NavigableList.svelte
<script lang="ts">
  import { afterUpdate } from 'svelte'

  import { getParentNavigable, Props, setChildrenNavigable } from '../../navigation'
  import InternalNavWrapper from '../InternalNavWrapper.svelte'
  import { NavigableList } from './NavigableList'

  export let hasFocusPriority: Props<NavigableList>['hasFocusPriority'] = null

  const list = new NavigableList(getParentNavigable(), { hasFocusPriority })

  setChildrenNavigable(list)

  afterUpdate(() => list.updateProps({ hasFocusPriority }))

  export const requestFocus = () => list.requestFocus()
</script>

<InternalNavWrapper navId={list.id}>
  <slot nav={list} />
</InternalNavWrapper>

// hify-client/src/navigable/headless/NavigableList/NavigableList.vue
<script setup lang="ts">
import { getParentNavigable } from '@/navigable/navigation';
import { NavigableList, type NavigableListProps } from './NavigableList';
import InternalNavWrapper from '../InternalNavWrapper.vue';

const props = defineProps<NavigableListProps>()

const list = new NavigableList(getParentNavigable(), props)

defineExpose({ list })

defineSlots<{
	default(props: { list: NavigableList }): unknown
}>()
</script>

<template>
	<InternalNavWrapper :nav="list" :props>
		<slot :list />
	</InternalNavWrapper>
</template>
