// hify-client/src/views/SearchPage.vue
<script setup lang="ts">
import Run from '@/components/atoms/Run.vue';
import AlbumsRow from '@/components/molecules/AlbumsRow.vue';
import ArtistsRow from '@/components/molecules/ArtistsRow.vue';
import TracksRow from '@/components/molecules/TracksRow.vue';
import { logFatal, logInfo } from '@/global/stores/debugger';
import { gqlClient } from '@/global/urql-client';
import { getRouteParam } from '@/global/utils';
import { graphql } from '@/graphql/generated';
import type { SearchPageQuery } from '@/graphql/generated/graphql';
import SimpleNavigableItem from '@/navigable/headless/SimpleNavigableItem/SimpleNavigableItem.vue';
import type { SimpleNavigableItem as SimpleNavigableItemClass } from '@/navigable/headless/SimpleNavigableItem/SimpleNavigableItem';
import { onMounted, ref } from 'vue';

const MAX_RESULTS_PER_CATEGORY = 50

async function onInput() {
  const searchTerms = query.value.trim()

  if (searchTerms.length === 0) {
    return
  }

  logInfo(`Performing search "${searchTerms}"...`)

  const start = Date.now()

  const { data, error } = await gqlClient.query(
    graphql(`
      query SearchPage($input: String!, $limit: Int!) {
        search(input: $input, limit: $limit) {
          tracks {
            ...AudioTrack
          }
          albums {
            ...Album
          }
          artists {
            ...Artist
          }
        }
      }
    `),
    {
      input: searchTerms,
      limit: MAX_RESULTS_PER_CATEGORY
    }
  )

  logInfo(`Performed search "${searchTerms}" in ${Date.now() - start} ms`)

  if (!data) {
    logFatal('Failed to perform search', error)
  }

  results.value = data.search
}

const query = ref(getRouteParam('query', ''))
const results = ref<SearchPageQuery['search'] | null>(null)
const inputRef = ref<HTMLInputElement | null>(null)
const navItem = ref<SimpleNavigableItemClass | null>(null)

onMounted(() => {
  if (!navItem.value) {
    logFatal('Nav item reference not initialized yet')
  }

  navItem.value.requestFocus()
})
</script>

<template>
  <div class="search-container">
    <SimpleNavigableItem @focus="inputRef?.focus()" @unfocus="inputRef?.blur()" v-slot="{ item }">
      <Run :run="() => { navItem = item }" />
      <input class="search" type="text" ref="inputRef" v-model="query" @input="onInput" @change="onInput" />
    </SimpleNavigableItem>
  </div>

  <div v-if="results">
    <h2>Tracks {{ results.tracks.length }}</h2>

    <TracksRow :tracks="results.tracks" />

    <h2>Albums {{ results.albums.length }}</h2>

    <AlbumsRow :albums="results.albums" />

    <h2>Artists {{ results.artists.length }}</h2>

    <ArtistsRow :artists="results.artists" />
  </div>
</template>

<style scoped>
.search-container {
  padding: 10px;
  text-align: center;
}

.search {
  border: none;
  border-radius: 10px;
  outline: none;
  width: 33%;
  padding: 12px;
  font-size: 1.2rem;
}
</style>

// hify-client/src/pages/SearchPage/SearchPage.svelte
<script lang="ts">
  import { onMount } from 'svelte'

  import { AsyncSearchPage, SearchPageQuery } from '../../graphql/generated'

  import { logInfo } from '../../stores/debugger'

  import SimpleNavigableItem from '../../navigable/SimpleNavigableItem/SimpleNavigableItem.svelte'

  import { RequestFocus } from '../../navigable/navigation'
  import TracksRow from '../../molecules/TracksRow/TracksRow.svelte'
  import AlbumsRow from '../../molecules/AlbumsRow/AlbumsRow.svelte'
  import ArtistsRow from '../../molecules/ArtistsRow/ArtistsRow.svelte'
  import ItemStyleLayer from '../../navigable/SimpleNavigableItem/ItemStyleLayer.svelte'

  export let searchTerms: string = ''

  const MAX_RESULTS_PER_CATEGORY = 50

  async function onChange() {
    if (searchTerms.trim().length === 0) {
      return
    }

    logInfo(`Performing search "${searchTerms}"...`)
    const start = Date.now()

    const res = await AsyncSearchPage({
      variables: {
        limit: MAX_RESULTS_PER_CATEGORY,
        input: searchTerms,
      },
    })

    results = res.data.search

    logInfo(`Received results for search "${searchTerms}" in ${Date.now() - start} ms.`)
  }

  if (searchTerms.length > 0) {
    onChange()
  }

  let results: SearchPageQuery['search'] | null = null

  let searchField: HTMLInputElement

  let requestFocus: RequestFocus

  onMount(() => requestFocus())
</script>

<div class="search-container">
  <SimpleNavigableItem
    onFocus={() => searchField.focus()}
    onUnfocus={() => searchField?.blur()}
    bind:requestFocus
    display="transparent"
    noPadding
    notRounded
  >
    <input
      class="search"
      type="text"
      bind:this={searchField}
      bind:value={searchTerms}
      on:input={onChange}
      on:change={onChange}
    />
  </SimpleNavigableItem>
</div>

{#if results}
  <h2>Tracks ({results.tracks.length})</h2>

  <TracksRow tracks={results.tracks} />

  <h2>Albums ({results.albums.length})</h2>

  <AlbumsRow albums={results.albums} />

  <h2>Artists ({results.artists.length})</h2>

  <ArtistsRow artists={results.artists} />
{/if}

<style>
  .search-container {
    padding: 10px;
    text-align: center;
  }

  .search {
    border: none;
    border-radius: 10px;
    outline: none;
    width: 33%;
    padding: 12px;
    font-size: 1.2rem;
  }
</style>
