// hify-client/src/pages/ArtistPage/ArtistPage.svelte
<script lang="ts">
  import LoadingIndicator from '@atoms/LoadingIndicator/LoadingIndicator.svelte'
  import MixButton from '@atoms/MixButton/MixButton.svelte'
  import { AsyncArtistPage, MixOrdering } from '@graphql/generated'

  import ArtistAlbums from './ArtistAlbums.svelte'
  import ArtistTrackParticipations from './ArtistTrackParticipations.svelte'

  export let artistId: string

  const artist = AsyncArtistPage({
    variables: { artistId },
  }).then((res) => res.data.artist)
</script>

{#await artist}
  <LoadingIndicator />
{:then artist}
  {#if !artist}
    <h2>Artist was not found!</h2>
  {:else}
    <h2>Artist: {artist.name}</h2>

    <MixButton
      mixParams={{
        source: { allTracks: null },
        ordering: MixOrdering.Random,
        minRating: 8,
        fromArtists: [artistId],
      }}
    />

    <ArtistAlbums {artistId} />

    <ArtistTrackParticipations {artistId} />
  {/if}
{:catch e}
  <h2>Failed: {e.message}</h2>
{/await}

// hify-client/src/views/ArtistPage.vue
<script setup lang="ts">
import LoadingIndicator from '@/components/atoms/LoadingIndicator.vue';
import MixButton from '@/components/atoms/MixButton.vue';
import { getRouteParam } from '@/global/utils';
import { graphql } from '@/graphql/generated';
import { MixOrdering } from '@/graphql/generated/graphql';
import { useQuery } from '@urql/vue';
import ArtistAlbums from './Artist/ArtistAlbums.vue';
import ArtistTrackParticipations from './Artist/ArtistTrackParticipations.vue';

const artistId = getRouteParam('id')

const { data, fetching } = useQuery({
  query: graphql(`
    query ArtistPage($artistId: String!) {
      artist(id: $artistId) {
        name
      }
    }
  `),
  variables: {
    artistId
  }
})
</script>

<template>
  <LoadingIndicator v-if="fetching" />

  <h2 v-else-if="data && !data.artist">Artist was not found</h2>

  <template v-else-if="data?.artist">
    <h2>Artist: {{ data.artist.name }}</h2>

    <MixButton :mix-params="{
      source: { allTracks: '-' },
      ordering: MixOrdering.Random,
      minRating: 8,
      fromArtists: [artistId],
    }" />

    <ArtistAlbums :artist-id />

    <ArtistTrackParticipations :artist-id />
  </template>
</template>
