// hify-client/src/pages/HomePage/HomePage.svelte
<script lang="ts">
  import { navigate } from 'svelte-navigator'
  import Button from '../../atoms/Button/Button.svelte'
  import MixButton from '../../atoms/MixButton/MixButton.svelte'
  import Row from '../../navigable/ui/molecules/Row/Row.svelte'
  import { AsyncHomePage } from '../../graphql/generated'
  import TracksRow from '../../molecules/TracksRow/TracksRow.svelte'
  import { ROUTES } from '../../routes'
  import IndexUpdater from './IndexUpdater.svelte'
  import LoadingIndicator from '../../atoms/LoadingIndicator/LoadingIndicator.svelte'
  import StatsBox from '../../molecules/StatsBox/StatsBox.svelte'
  import Centered from '../../atoms/Centered/Centered.svelte'
  import AlbumsRow from '../../molecules/AlbumsRow/AlbumsRow.svelte'
  import { LARGE_MIX_TRACKS_QTY, MIN_GREAT_RATING } from '../../constants'

  async function fetchFeed() {
    const res = await AsyncHomePage({
      variables: {
        randomItemsParams: {
          minRating: 8,
          maxItems: 25,
        },
      },

      fetchPolicy: 'no-cache',
    })

    return res.data.generateFeed
  }

  function onUpdated() {
    feed = fetchFeed()
  }

  let feed = fetchFeed()
  let statsBox = false
</script>

{#await feed}
  <LoadingIndicator />
{:then { lastListenedTo, periodicallyPopularTracks, mostRecentAlbums }}
  <Centered>
    <h2>Welcome!</h2>

    <MixButton mixParams={{ minRating: MIN_GREAT_RATING, maxTracks: LARGE_MIX_TRACKS_QTY }} />
  </Centered>

  <Centered>
    <h3>Tracks you currently like to listen to:</h3>
  </Centered>

  <TracksRow tracks={periodicallyPopularTracks} />

  <Centered>
    <h3>Last songs you listened to:</h3>
  </Centered>

  <TracksRow tracks={lastListenedTo} />

  <Centered>
    <h3>Last albums to collection:</h3>
  </Centered>

  <AlbumsRow albums={mostRecentAlbums} />

  <!-- <h3>Albums you like to listen to:</h3>

  <AlbumsRow albums={popularAlbums} />

  <h3>Artists you like to listen to:</h3>

  <ArtistsRow artists={popularArtists} /> -->

  <!-- <h3>Random great albums:</h3>

  <AlbumsRow albums={randomGreatAlbums} />

  <h3>Random great artists:</h3>

  <ArtistsRow artists={randomGreatArtists} /> -->

  <Centered>
    <h3>Tools</h3>
  </Centered>

  <Row>
    <IndexUpdater {onUpdated} />
    <Button onPress={() => navigate(ROUTES.devTools)} fullHeight>👷 Devtools</Button>
    <Button
      onPress={() => {
        statsBox = !statsBox
      }}>Show me some stats</Button
    >
  </Row>

  {#if statsBox}
    <Row>
      <StatsBox />
    </Row>
  {/if}
{:catch e}
  <h1>Failed to load homepage: {e.message}</h1>
{/await}

// hify-client/src/views/HomePage.vue
<script setup lang="ts">
import Button from '@/components/atoms/Button.vue';
import Centered from '@/components/atoms/Centered.vue';
import IndexUpdater from '@/components/atoms/IndexUpdater.vue';
import LoadingIndicator from '@/components/atoms/LoadingIndicator.vue';
import MixButton from '@/components/atoms/MixButton.vue';
import AlbumsRow from '@/components/molecules/AlbumsRow.vue';
import TracksRow from '@/components/molecules/TracksRow.vue';
import { MIN_GREAT_RATING } from '@/global/constants';
import { graphql } from '@/graphql/generated';
import { MixOrdering, type HomePageQuery } from '@/graphql/generated/graphql';
import Row from '@/navigable/ui/molecules/Row/Row.vue';
import router from '@/router';
import { useQuery } from '@urql/vue';
import { computed, ref } from 'vue';

const { data, executeQuery } = useQuery({
  query: graphql(`
    query HomePage($randomItemsParams: FeedParams!) {
      generateFeed(input: $randomItemsParams) {
        lastListenedTo {
          ...AudioTrack
        }

        periodicallyPopularTracks {
          ...AudioTrack
        }

        mostRecentAlbums {
          ...Album
        }
      }
    }
  `),
  variables: {
    randomItemsParams: {
      maxItems: 100,
      minRating: 8,
    }
  }
})


const feed = computed(() => data.value?.generateFeed)
const statsBox = ref(false)
</script>

<template>
  <LoadingIndicator v-if="!feed" />

  <template v-else>
    <Centered>
      <h2>Welcome!</h2>

      <MixButton :mixParams="{
        source: { allTracks: '-' },
        ordering: MixOrdering.Random,
        minRating: MIN_GREAT_RATING,
      }" />
    </Centered>

    <Centered>
      <h3>Tracks you currently like to listen to:</h3>
    </Centered>

    <TracksRow :tracks="feed.periodicallyPopularTracks" />

    <Centered>
      <h3>Last songs you listened to:</h3>
    </Centered>

    <TracksRow :tracks="feed.lastListenedTo" />

    <Centered>
      <h3>Last albums to collection:</h3>
    </Centered>

    <AlbumsRow :albums="feed.mostRecentAlbums" />

    <Centered>
      <h3>Tools</h3>
    </Centered>

    <Row>
      <IndexUpdater @updated="executeQuery" />
      <Button @press="router.push({ name: 'devtools' })">👷 Devtools</Button>
      <Button @press="statsBox = !statsBox">Show me some stats</Button>
    </Row>
  </template>
</template>
