// hify-client/src/views/Artist/ArtistTrackParticipations.vue
<script setup lang="ts">
import Centered from '@/components/atoms/Centered.vue'
import LoadingIndicator from '@/components/atoms/LoadingIndicator.vue'
import TracksFromAlbums from '@/components/organisms/TracksFromAlbums.vue'
import { gqlClient } from '@/global/urql-client'
import { noParallel } from '@/global/utils'
import { graphql } from '@/graphql/generated'
import type { ArtistTrackParticipationsQuery, AudioTrackFragment } from '@/graphql/generated/graphql'
import { logFatal } from '@/navigable'
import { onMounted, ref } from 'vue'

const { artistId } = defineProps<{ artistId: string }>()

const TRACKS_PER_LINE = 6
const LINES_PER_PAGE = 5

const feedMore = noParallel(async () => {
	if (currentPageInfo.value?.hasNextPage === false) {
		return
	}

	const { data, error } = await gqlClient.query(
		graphql(`
      query ArtistTrackParticipations($artistId: String!, $pagination: PaginationInput!) {
        artist(id: $artistId) {
          trackParticipations(pagination: $pagination) {
            nodes {
              ...AudioTrack
            }

            pageInfo {
              endCursor
              hasNextPage
            }
          }
        }
      }
    `),
		{
			artistId,
			pagination: {
				after: currentPageInfo.value?.endCursor,
				first: TRACKS_PER_LINE * LINES_PER_PAGE,
			},
		},
	)

	if (!data?.artist) {
		logFatal('Failed to fetch track participations', error)
	}

	currentPageInfo.value = data.artist.trackParticipations.pageInfo
	tracks.value.push(...data.artist.trackParticipations.nodes)
})

const currentPageInfo = ref<
	NonNullable<ArtistTrackParticipationsQuery['artist']>['trackParticipations']['pageInfo'] | null
>(null)

const tracks = ref<AudioTrackFragment[]>([])

onMounted(feedMore)
</script>

<template>
  <LoadingIndicator v-if="!currentPageInfo" :error="null /* TODO */" />

  <template v-else-if="tracks.length > 0">
    <Centered>
      <h3>Tracks from other artists' albums ({{ tracks.length }})</h3>
    </Centered>

    <TracksFromAlbums :tracks :has-more="currentPageInfo.hasNextPage" :feed-more show-artists-name />
  </template>
</template>

// hify-client/src/pages/ArtistPage/ArtistTrackParticipations.svelte
<script lang="ts">
import { AsyncArtistTrackParticipations, type AudioTrackFragment } from '@graphql/generated'

import Button from '@atoms/Button/Button.svelte'
import LoadingIndicator from '@atoms/LoadingIndicator/LoadingIndicator.svelte'
import TrackCard from '@molecules/TrackCard/TrackCard.svelte'
import Grid from '@navigable/ui/organisms/Grid/Grid.svelte'

export let artistId: string

const TRACKS_PER_LINE = 5
const LINES_PER_REQUEST = 5

let currentPageInfo: { endCursor?: string | null; hasNextPage: boolean } | null = null

const feedMore = async () => {
	if (currentPageInfo?.hasNextPage === false) {
		return currentPageInfo
	}

	const res = await AsyncArtistTrackParticipations({
		variables: {
			artistId,
			pagination: {
				after: currentPageInfo?.endCursor,
				first: TRACKS_PER_LINE * LINES_PER_REQUEST,
			},
		},
	}).then((res) => res.data.artist?.trackParticipations)

	if (!res) {
		throw new Error("Failed to fetch artist's data")
	}

	currentPageInfo = res.pageInfo
	tracks = [...tracks, ...res.nodes]

	return currentPageInfo
}

let tracks: AudioTrackFragment[] = []
</script>

{#await feedMore()}
  <LoadingIndicator />
{:then lastPageInfo}
  {#if tracks.length !== 0}
    <h3>Tracks from other artists' albums ({tracks.length})</h3>

    <Grid columns={TRACKS_PER_LINE}>
      {#each tracks as track}
        <TrackCard {track} {tracks} />
      {/each}
    </Grid>

    {#if lastPageInfo.hasNextPage}
      <Button onPress={() => void feedMore()}>Load more</Button>
    {/if}
  {/if}
{:catch e}
  <h2>Failed: {e.message}</h2>
{/await}
