// hify-client/src/components/molecules/TrackCard.vue
<script setup lang="ts">
import NavigableTrack from '../atoms/NavigableTrack.vue'
import type { EntryInPlaylist } from '@/global/context-menu-items'
import Card from './Card.vue'
import type { SimpleNavigableItemProps } from '@/navigable/headless/SimpleNavigableItem/SimpleNavigableItem'
import type { AudioTrackFragment } from '@/graphql/generated/graphql';

defineProps<{
    track: AudioTrackFragment,
    tracks: AudioTrackFragment[],
    inPlaylist?: EntryInPlaylist,
    onFocus?: SimpleNavigableItemProps['onFocus']
}>()

</script>

<template>
    <NavigableTrack :track :tracks :context="inPlaylist ? { context: 'playlist', entry: inPlaylist } : {
        context: 'normal'
    }" :on-focus>
        <Card :title="track.metadata.tags.title" art-type="album" :art-item="track.metadata.tags.album" />
    </NavigableTrack>

</template>

// hify-client/src/components/molecules/TrackCard/TrackCard.svelte
<script lang="ts">
import NavigableTrack from '@atoms/NavigableTrack/NavigableTrack.svelte'
import type { EntryInPlaylist } from '@globals/context-menu-items'
import type { AudioTrackFragment } from '@graphql/generated'
import Card from '@molecules/Card/Card.svelte'
import type { SimpleNavigableItemProps } from '@navigable/headless/SimpleNavigableItem/SimpleNavigableItem'

export let track: AudioTrackFragment
export let tracks: AudioTrackFragment[]
export let inPlaylist: EntryInPlaylist | null = null
export let onFocus: SimpleNavigableItemProps['onFocus'] = undefined
</script>

<NavigableTrack
  {track}
  {tracks}
  context={inPlaylist ? { context: 'playlist', entry: inPlaylist } : { context: 'normal' }}
  {onFocus}
>
  <Card title={track.metadata.tags.title} art={track.metadata.tags.album.art} />
</NavigableTrack>
