// hify-client/src/components/atoms/MixButton.vue
<script setup lang="ts">
import type { MixParams } from '@/graphql/generated/graphql';
import Button from './Button.vue';
import { generateAndPlayMix } from '@/global/stores/play-queue';
import { showContextMenu } from '@/navigable/ui/molecules/ContextMenu/ContextMenu';

defineProps<{
    mixParams: MixParams
}>()
</script>

<template>
    <Button @press="generateAndPlayMix(mixParams)" @long-press="showContextMenu([
        {
            label: 'Only with the best rating <3',
            onPress: () => void generateAndPlayMix({ ...mixParams, minRating: 10 }),
        }
    ])">
        Mix me some magic ✨
    </Button>
</template>

// hify-client/src/atoms/MixButton/MixButton.svelte
<script lang="ts">
  import Button from '../Button/Button.svelte'
  import { MixParams } from '../../graphql/generated'
  import { generateAndPlayMix } from './MixGenerator'
  import { showContextMenu } from '../../navigable/ui/molecules/ContextMenu/ContextMenu'

  export let mixParams: MixParams
</script>

<Button
  onPress={() => generateAndPlayMix(mixParams)}
  onLongPress={() =>
    showContextMenu([
      {
        label: 'Only with the best rating <3',
        onPress: () => generateAndPlayMix({ ...mixParams, minRating: 100 }),
      },
    ])}>Mix me some magic ✨</Button
>
