// hify-client/src/navigable/ui/molecules/Column/Column.vue
<script setup lang="ts">
import type { NavigableList as NavigableListClass, NavigableListProps } from '@/navigable/headless/NavigableList/NavigableList'
import NavigableList from '@/navigable/headless/NavigableList/NavigableList.vue'

defineProps<NavigableListProps>()

defineSlots<{
  default(props: { column: NavigableListClass }): unknown
}>()
</script>

<template>
  <div class="flex flex-col overflow-x-auto">
    <NavigableList v-slot="{ list }">
      <slot :column="list" />
    </NavigableList>
  </div>
</template>

// hify-client/src/atoms/Column/Column.svelte
<script lang="ts">
  import NavigableList from '../../navigable/NavigableList/NavigableList.svelte'
  import { RequestFocus } from '../../navigable/navigation'

  export let requestFocus: RequestFocus
</script>

<div class="column">
  <NavigableList bind:requestFocus>
    <slot />
  </NavigableList>
</div>

<style>
  .column {
    display: flex;
    flex-direction: column;
    overflow-x: auto;
  }
</style>
