// hify-client/src/components/atoms/IndexUpdater.vue
<script setup lang="ts">
import Button from '@/components/atoms/Button.vue'
import { UpdateIndexDocument } from '@/graphql/generated/graphql'
import { useMutation } from '@urql/vue';
import { watch } from 'vue';

const emit = defineEmits<{
    updated: []
}>()

const { data, error, fetching, executeMutation } = useMutation(UpdateIndexDocument)

watch(data, () => emit('updated'))
</script>

<template>
    <Button @press="executeMutation({})" :disabled="fetching">
        Update the index (this might take a while)
    </Button>

    <span v-if="fetching">⌛</span>
    <span v-if="data">✅</span>
    <span v-if="error">❌ {{ error.message }}</span>
</template>

// hify-client/src/pages/HomePage/IndexUpdater.svelte
<script lang="ts">
  import Button from '../../atoms/Button/Button.svelte'
  import { IndexUpdater } from '../../graphql/generated'

  function updateIndex() {
    isUpdating = true
    updateResult = null

    IndexUpdater({ variables: {} })
      .then(() => {
        updateResult = { type: 'ok' }
      })
      .catch((err) => {
        updateResult = { type: 'err', err }
      })
      .finally(() => {
        isUpdating = false
      })
  }

  let isUpdating = false
  let updateResult: { type: 'ok' } | { type: 'err'; err: Error } | null = null
</script>

<Button onPress={() => updateIndex()} disabled={isUpdating}>Update the index (this might take a while)</Button>

<span>
  {#if isUpdating}
    ⌛
  {/if}

  {#if updateResult?.type === 'ok'}
    ✅
  {:else if updateResult?.type === 'err'}
    ❌ {updateResult.err.message}
  {/if}
</span>
