// hify-client/src/components/atoms/Checkbox.vue
<script setup lang="ts">
import { ref } from 'vue';
import Button, { type ButtonProps } from './Button.vue';

const model = defineModel<boolean>()
const props = defineProps<ButtonProps>()

const checkboxRef = ref<HTMLInputElement | null>(null)
</script>

<template>
    <Button v-bind="props" @press="model = !model">
        <input type="checkbox" v-model="model" ref="checkboxRef" />
        <slot />
    </Button>
</template>

// hify-client/src/atoms/Checkbox/Checkbox.svelte
<script lang="ts">
  import Button from '../Button/Button.svelte'

  export let checked = false
  export let onChange: ((checked: boolean) => void) | null = null

  function onPress() {
    checked = !checked
    onChange?.(checked)
  }
</script>

<Button {onPress}>
  <input type="checkbox" {checked} />
  <slot />
</Button>
