// hify-client/src/pages/ArtistPage/ArtistAlbums.svelte
<script lang="ts">
import { AlbumCardFragment, AsyncArtistAlbums } from '@graphql/generated'

import Grid from '@navigable/ui/organisms/Grid/Grid.svelte'
import AlbumCard from '@molecules/AlbumCard/AlbumCard.svelte'
import Button from '@atoms/Button/Button.svelte'
import LoadingIndicator from '@atoms/LoadingIndicator/LoadingIndicator.svelte'

export let artistId: string

const ALBUMS_PER_LINE = 5
const LINES_PER_REQUEST = 5

let currentPageInfo: { endCursor?: string | null; hasNextPage: boolean } | null = null

const feedMore = async () => {
	if (currentPageInfo?.hasNextPage === false) {
		return currentPageInfo
	}

	const res = await AsyncArtistAlbums({
		variables: {
			artistId,
			pagination: {
				after: currentPageInfo?.endCursor,
				first: ALBUMS_PER_LINE * LINES_PER_REQUEST,
			},
		},
	}).then((res) => res.data.artist?.albums)

	if (!res) {
		throw new Error("Failed to fetch artist's data")
	}

	currentPageInfo = res.pageInfo
	albums = [...albums, ...res.nodes]

	return currentPageInfo
}

let albums: AlbumCardFragment[] = []
</script>

{#await feedMore()}
  <LoadingIndicator />
{:then lastPageInfo}
  {#if albums.length === 0}
    <h3>No album</h3>
  {:else}
    <h3>Albums ({albums.length})</h3>

    <Grid columns={ALBUMS_PER_LINE}>
      {#each albums as album}
        <AlbumCard {album} />
      {/each}
    </Grid>

    {#if lastPageInfo.hasNextPage}
      <Button onPress={() => void feedMore()}>Load more</Button>
    {/if}
  {/if}
{:catch e}
  <h2>Failed: {e.message}</h2>
{/await}

// hify-client/src/views/Artist/ArtistAlbums.vue
<script setup lang="ts">
import Button from '@/components/atoms/Button.vue';
import LoadingIndicator from '@/components/atoms/LoadingIndicator.vue';
import AlbumCard from '@/components/molecules/AlbumCard.vue';
import { logFatal } from '@/global/stores/debugger';
import { gqlClient } from '@/global/urql-client';
import { graphql } from '@/graphql/generated';
import type { AlbumFragment, AlbumsPageQuery, ArtistAlbumsQuery, ArtistPageQuery } from '@/graphql/generated/graphql';
import Grid from '@/navigable/ui/organisms/Grid.vue';
import { onMounted, ref } from 'vue';

const { artistId } = defineProps<{ artistId: string }>()

const ALBUMS_PER_LINE = 6
const LINES_PER_PAGE = 5

async function feedMore() {
  if (currentPageInfo.value?.hasNextPage === false) {
    return
  }

  const { data, error } = await gqlClient.query(
    graphql(`
      query ArtistAlbums($artistId: String!, $pagination: PaginationInput!) {
        artist(id: $artistId) {
          albums(pagination: $pagination) {
            nodes {
              ...Album
            }

            pageInfo {
              endCursor
              hasNextPage
            }
          }
        }
      }
    `),
    {
      artistId,
      pagination: {
        after: currentPageInfo.value?.endCursor,
        first: ALBUMS_PER_LINE * LINES_PER_PAGE
      }
    }
  )

  if (!data?.artist) {
    logFatal('Failed to fetch albums list', error)
  }

  currentPageInfo.value = data.artist.albums.pageInfo
  albums.value.push(...data.artist.albums.nodes)
}

const currentPageInfo = ref<NonNullable<ArtistAlbumsQuery['artist']>['albums']['pageInfo'] | null>(null)

const albums = ref<AlbumFragment[]>([])

onMounted(feedMore)
</script>

<template>
  <LoadingIndicator v-if="!currentPageInfo" />

  <h3 v-else-if="albums.length === 0">No album</h3>

  <template v-else>
    <h3>Albums ({{ albums.length }})</h3>

    <Grid :columns="ALBUMS_PER_LINE">
      <AlbumCard v-for="album in albums" :key="album.id" :album enforce-max-width />
    </Grid>

    <Button v-if="currentPageInfo.hasNextPage" @press="feedMore()">
      Load more
    </Button>
  </template>
</template>
