// hify-client/src/views/NowPlaying/NowPlayingBottomPanel.vue
<script setup lang="ts">
import ProgressiveRow, { type ProgressiveRowExposeType } from '@/components/molecules/ProgressiveRow.vue';
import ModifiableTrackRating from '@/components/atoms/ModifiableTrackRating.vue';
import AudioProgressBar from '@/components/atoms/AudioProgressBar.vue';
import With from '@/components/atoms/With.vue';
import Card from '@/components/molecules/Card.vue';
import { ctxMenuOptions } from '@/global/context-menu-items';
import { humanReadableDuration, readableAudioPaused, readableAudioProgress, setPlayingAudioProgressRelative, toggleAudioPlayback } from '@/global/stores/audio-player';
import { enableOpacitor } from '@/global/stores/opacitor';
import { currentTrack, playTrackFromCurrentQueue, readablePlayQueue } from '@/global/stores/play-queue';
import { formatDate } from '@/global/utils';
import type { AudioTrackFragment } from '@/graphql/generated/graphql';
import router from '@/router';
import { ref, watch } from 'vue';
import { getAlbumArtUrl } from '@/global/constants';
import NavigableList from '@/navigable/vue/components/NavigableList.vue';
import NavigableRow from '@/navigable/vue/components/NavigableRow.vue';
import NavigableItem from '@/navigable/vue/components/NavigableItem.vue';
import { showContextMenu } from '@/global/stores/context-menu';

const isQueueFocused = ref(false)

function showTrackCtxMenu(track: AudioTrackFragment, position: number) {
  showContextMenu(
    ctxMenuOptions.forTrack(
      track,
      { fromMixId: null },
      {
        context: 'queue',
        isCurrent: readablePlayQueue.value.position === position,
        position,
        totalTracks: readablePlayQueue.value.tracks.length,
        onQueueEdition: () => queueGalleryRef.value?.requestFocus(position)
      },
    ),
  )
}

const queueGalleryRef = ref<ProgressiveRowExposeType | null>(null)

watch(() => [queueGalleryRef.value, readablePlayQueue.value.position] as const, ([gallery, position]) => {
  if (gallery !== null && position !== null) {
    gallery.jumpUnfocusedPosition(position)
  }
})
</script>

<template>
  <div class="player-bottom" :class="{ isQueueFocused, noCurrentTrack: !currentTrack }">
    <NavigableList>
      <NavigableList v-if="currentTrack">
        <With :data="{ currentTrack, tags: currentTrack.metadata.tags }" v-slot="{ data: { currentTrack, tags } }">
          <div class="buttons">
            <NavigableRow>
              <NavigableItem @press="router.push({ name: 'search', params: { query: tags.title } })">
                <div class="track-info">🎵 {{ tags.title }}</div>
              </NavigableItem>

              <NavigableItem @press="router.push({ name: 'album', params: { id: tags.album.id } })">
                <div class="track-info">💿 {{ tags.album.name }}</div>
              </NavigableItem>

              <NavigableItem v-if="tags.date" just-for-style>
                <div class="track-info">🕒 {{ formatDate(tags.date) }}</div>
              </NavigableItem>

              <NavigableItem v-for="artist in tags.artists" :key="artist.id"
                @press="router.push({ name: 'artist', params: { id: artist.id } })">
                <div class="track-info">🎤 {{ artist.name }}</div>
              </NavigableItem>

              <NavigableItem @press="enableOpacitor = !enableOpacitor">
                <div class="option-button">
                  <span v-if="enableOpacitor">🔲</span>
                  <span v-else>🔳</span>
                </div>
              </NavigableItem>

              <ModifiableTrackRating :track="currentTrack" />
            </NavigableRow>
          </div>

          <div class="player-time">
            <div class="track-progress">
              <span v-if="readableAudioProgress !== null">
                {{ humanReadableDuration(readableAudioProgress) }}
              </span>
              <span v-else>
                --:--
              </span>

              <span v-if="readableAudioPaused">⏸️</span>
            </div>

            <div class="track-duration">
              {{ humanReadableDuration(currentTrack.metadata.duration) }}
            </div>
          </div>

          <div class="progress-range">
            <AudioProgressBar :max="currentTrack.metadata.duration" :value="readableAudioProgress ?? 0"
              @press="toggleAudioPlayback"
              @direction="dir => setPlayingAudioProgressRelative(dir === 'left' ? -30 : 30)" />
          </div>
        </With>
      </NavigableList>

      <div class="play-queue-gallery">
        <NavigableList>
          <ProgressiveRow ref="queueGalleryRef" :items="readablePlayQueue.tracks" idProp="idInQueue"
            :initialPosition="readablePlayQueue.position ?? 0" @item-press="(_, pos) => playTrackFromCurrentQueue(pos)"
            @item-long-press="showTrackCtxMenu" @focus-change="focused => { isQueueFocused = focused }"
            v-slot="{ item: track, position, focused }">
            <Card :title="track.metadata.tags.title" :box-size="80" :art-url="getAlbumArtUrl(track.metadata.tags.album)"
              :opacity="readablePlayQueue.position === position ? 1 : focused ? 0.7 : 0.2" />
          </ProgressiveRow>
        </NavigableList>
      </div>
    </NavigableList>
  </div>
</template>

<style scoped>
.player-bottom {
  position: fixed;

  left: 0;
  right: 0;
  bottom: -100px;

  padding-left: 5%;
  padding-right: 5%;
  padding-bottom: 1%;

  background-image: linear-gradient(to bottom, rgba(255, 0, 0, 0), rgba(30, 30, 30, 1));

  transition: bottom 0.3s;
}

.player-bottom.isQueueFocused,
.player-bottom.noCurrentTrack {
  bottom: 0px;

  transition: bottom 0.3s;
}

.buttons {
  display: flex;
  flex-direction: row;
  align-items: end;
  font-size: 1.2rem;
}

.track-info,
.option-button {
  padding: 5px;
  align-self: stretch;
}

.progress-range,
.progress-range :global(input) {
  width: calc(100% - 5px);
}

.player-time {
  display: flex;
  flex-direction: row;
  justify-content: space-between;
  padding: 0px 10px;
  transition: all 1s;
}
</style>

// hify-client/src/pages/NowPlayingPage/NowPlayingBottomPanel.svelte
<script lang="ts">
import { bind, formatDate } from '@globals/utils'
import { navigate } from 'svelte-navigator'

import {
	humanReadableDuration,
	readableAudioPaused,
	readableAudioProgress,
	setPlayingAudioProgress,
	toggleAudioPlayback,
} from '@stores/audio-player'
import { currentTrack, playTrackFromCurrentQueue, queuePosition, readablePlayQueue } from '@stores/play-queue'

import type { AudioTrackFragment } from '@graphql/generated'

import ModifiableTrackRating from '@atoms/ModifiableTrackRating/ModifiableTrackRating.svelte'
import ProgressRange from '@atoms/ProgressRange/ProgressRange.svelte'
import { ctxMenuOptions } from '@globals/context-menu-items'
import Card from '@molecules/Card/Card.svelte'
import ProgressiveRow from '@molecules/ProgressiveRow/ProgressiveRow.svelte'
import NavigableRow from '@navigable/headless/NavigableRow/NavigableRow.svelte'
import SimpleNavigableItem from '@navigable/headless/SimpleNavigableItem/SimpleNavigableItem.svelte'
import Column from '@navigable/ui/molecules/Column/Column.svelte'
import { showContextMenu } from '@navigable/ui/molecules/ContextMenu/ContextMenu'
import { ROUTES } from '@root/routes'
import { enableOpacitor } from '@stores/opacitor'

let isQueueFocused = false

// function toggleWaveForm() {
//   showWaveform = !showWaveform
// }

// let showWaveform = false

function showTrackCtxMenu(track: AudioTrackFragment, position: number) {
	showContextMenu(
		ctxMenuOptions.forTrack(
			track,
			{ fromMixId: null },
			{
				context: 'queue',
				isCurrent: $queuePosition === position,
				position,
				totalTracks: $readablePlayQueue.tracks.length,
			},
		),
	)
}

function setQueueFocused(isFocused: boolean) {
	isQueueFocused = isFocused
}
</script>

<div class="player-bottom" class:isQueueFocused class:noCurrentTrack={!$currentTrack}>
  <Column>
    <Column>
      {#if $currentTrack}
        {@const tags = $currentTrack.metadata.tags}
        {@const album = tags.album}
        {@const artists = tags.artists.length > 0 ? tags.artists : album.albumArtists}

        <!-- {#if showWaveform}
          <TrackWaveForm
            track={currentTrack}
            progress={($readableAudioProgress ?? 0) / currentTrack.metadata.duration}
            width="100%"
            height="50px"
          />
        {/if} -->

        <div class="buttons">
          <NavigableRow>
            <SimpleNavigableItem onPress={bind(tags, (tags) => void navigate(ROUTES.searchTerms(tags.title)))}>
              <div class="track-info">🎵 {tags.title}</div>
            </SimpleNavigableItem>
            <SimpleNavigableItem onPress={bind(album, (album) => void navigate(ROUTES.album(album.id)))}>
              <div class="track-info">💿 {album.name}</div>
            </SimpleNavigableItem>
            {#if tags.date}
              <SimpleNavigableItem justForStyle>
                <div class="track-info">🕒 {formatDate(tags.date)}</div>
              </SimpleNavigableItem>
            {/if}

            {#each artists as artist}
              <SimpleNavigableItem onPress={bind(artist.id, (id) => navigate(ROUTES.artist(id)))}>
                <div class="track-info">🎤 {artist.name}</div>
              </SimpleNavigableItem>
            {/each}

            <SimpleNavigableItem onPress={() => enableOpacitor.update(enabled => !enabled)}>
              <div class="option-button">
                {#if $enableOpacitor}
                  🔲
                {:else}
                  🔳
                {/if}
              </div>
            </SimpleNavigableItem>

            <!-- TODO: This works perfectly, but waiting for performance improvements
                       before displaying it again -->
            <!-- <SimpleNavigableItem onPress={toggleWaveForm}>
              <div class="track-action">∿ Waveform</div>
            </SimpleNavigableItem> -->

            <ModifiableTrackRating track={$currentTrack} />
          </NavigableRow>
        </div>

        <div class="player-time">
          <div class="track-progress">
            {#if $readableAudioProgress !== null}
              {humanReadableDuration($readableAudioProgress)}
            {:else}
              --:--
            {/if}
            {#if $readableAudioPaused}
              ⏸️
            {/if}
          </div>
          <div class="track-duration">
            {humanReadableDuration($currentTrack.metadata.duration)}
          </div>
        </div>

        <div class="progress-range">
          <ProgressRange
            max={$currentTrack.metadata.duration}
            value={$readableAudioProgress}
            onChange={setPlayingAudioProgress}
            onPress={toggleAudioPlayback}
            directionalAmount={30}
          />
        </div>
      {/if}
    </Column>

    <div class="play-queue-gallery">
      <Column>
        <ProgressiveRow
          items={$readablePlayQueue.tracks}
          idProp="idInQueue"
          initialPosition={$queuePosition ?? 0}
          onItemPress={(_, pos) => playTrackFromCurrentQueue(pos)}
          onItemLongPress={showTrackCtxMenu}
          onFocusChange={setQueueFocused}
          let:item={track}
          let:position
          let:focused
        >
          <Card
            title={track.metadata.tags.title}
            subtitle={null}
            boxSize={80}
            art={track.metadata.tags.album.art}
            opacity={$queuePosition === position ? 1 : focused ? 0.7 : 0.2}
          />
        </ProgressiveRow>
      </Column>
    </div>
  </Column>
</div>

<style>
  .player-bottom {
    position: fixed;

    left: 0;
    right: 0;
    bottom: -100px;

    padding-left: 5%;
    padding-right: 5%;
    padding-bottom: 1%;

    background-image: linear-gradient(to bottom, rgba(255, 0, 0, 0), rgba(30, 30, 30, 1));

    transition: bottom 0.3s;
  }

  .player-bottom.isQueueFocused,
  .player-bottom.noCurrentTrack {
    bottom: 0px;

    transition: bottom 0.3s;
  }

  .buttons {
    display: flex;
    flex-direction: row;
    align-items: end;
    font-size: 1.2rem;
  }

  .track-info, .option-button {
    padding: 5px;
    align-self: stretch;
  }

  .progress-range,
  .progress-range :global(input) {
    width: calc(100% - 5px);
  }

  .player-time {
    display: flex;
    flex-direction: row;
    justify-content: space-between;
    padding: 0px 10px;
    transition: all 1s;
  }
</style>
