// hify-client/src/organisms/Grid/Grid.svelte
<script lang="ts">
  import { NavigableGridProps } from '../../navigable/NavigableGrid/NavigableGrid'
  import NavigableGrid from '../../navigable/NavigableGrid/NavigableGrid.svelte'

  export let columns: number
  export let lazyLoader: NavigableGridProps['lazyLoader'] = undefined

  const columnsSize = new Array(columns).fill(`${100 / columns}%`).join(' ')
</script>

<div class="container" style="--columns-size: {columnsSize}">
  <NavigableGrid {columns} {lazyLoader}>
    <slot />
  </NavigableGrid>
</div>

<style>
  .container {
    display: grid;
    grid-template-columns: var(--columns-size);
    text-align: center;
  }
</style>

// hify-client/src/navigable/ui/organisms/Grid.vue
<script setup lang="ts">
import type { NavigableGridProps } from '@/navigable/headless/NavigableGrid/NavigableGrid'
import NavigableGrid from '@/navigable/headless/NavigableGrid/NavigableGrid.vue'
import { computed } from 'vue';

const props = defineProps<NavigableGridProps>()

const columnsSize = computed(() => new Array(props.columns).fill(`${100 / props.columns}%`).join(' '))
</script>

<template>
  <div class="container" :style="`--columns-size: ${columnsSize}`">
    <NavigableGrid v-bind="props">
      <slot />
    </NavigableGrid>
  </div>
</template>

<style scoped>
.container {
  display: grid;
  grid-template-columns: var(--columns-size);
  text-align: center;
}
</style>
