// hify-client/src/views/HistoryPage.vue
<script setup lang="ts">
import { onMounted, ref } from 'vue'
import TracksGrid from '@/components/molecules/TracksGrid.vue'
import { GRID_TRACKS_PER_ROW, GRID_TRACKS_PRELOAD_ROWS } from '@/global/constants'
import { gqlClient } from '@/global/urql-client'
import { noParallel } from '@/global/utils'
import { graphql } from '@/graphql/generated'
import type { AudioTrackFragment, HistoryPageQuery } from '@/graphql/generated/graphql'
import { logFatal } from '@/navigable'

const feedMore = noParallel(async () => {
	if (currentPageInfo.value?.hasNextPage === false) {
		return
	}

	const { data, error } = await gqlClient.query(
		graphql(`
      query HistoryPage($pagination: PaginationInput!) {
        history(pagination: $pagination) {
          nodes {
            ...AudioTrack
          }

          pageInfo {
            endCursor
            hasNextPage
          }
        }
      }
    `),
		{
			pagination: {
				after: currentPageInfo.value?.endCursor,
				first: GRID_TRACKS_PER_ROW * GRID_TRACKS_PRELOAD_ROWS,
			},
		},
	)

	if (!data) {
		logFatal('Failed to fetch albums list', error)
	}

	currentPageInfo.value = data.history.pageInfo
	tracks.value.push(...data.history.nodes)
})

const currentPageInfo = ref<HistoryPageQuery['history']['pageInfo'] | null>(null)

const tracks = ref<AudioTrackFragment[]>([])

onMounted(feedMore)
</script>

<template>
	<TracksGrid
		:tracks
		@feed-more="feedMore"
	/>
</template>

// hify-client/src/pages/HistoryPage/HistoryPage.svelte
<script lang="ts">
  import { AsyncHistoryPage, AudioTrackFragment } from '@graphql/generated'
  import LoadingIndicator from '@atoms/LoadingIndicator/LoadingIndicator.svelte'
  import { GRID_TRACKS_PER_ROW } from '../../constants'
  import TracksGrid from '@molecules/TracksGrid/TracksGrid.svelte'

  const LINES_PER_PAGE = 5

  let currentPageInfo: { endCursor?: string | null; hasNextPage: boolean } | null = null

  const feedMore = async () => {
    if (currentPageInfo?.hasNextPage === false) {
      return
    }

    const res = await AsyncHistoryPage({
      variables: {
        pagination: {
          after: currentPageInfo?.endCursor,
          first: GRID_TRACKS_PER_ROW * LINES_PER_PAGE,
        },
      },
      fetchPolicy: 'no-cache',
    })

    currentPageInfo = res.data.history.pageInfo
    tracks = [...tracks, ...res.data.history.nodes]
  }

  let tracks: AudioTrackFragment[] = []
</script>

{#await feedMore()}
  <LoadingIndicator />
{:then _}
  <h2>History</h2>

  <TracksGrid {tracks} {feedMore} />
{:catch e}
  <h2>Failed: {e.message}</h2>
{/await}
