// hify-client/src/navigable/NavigablePage/NavigablePage.svelte
<script lang="ts">
  import { handleKeyboardEvent, usePageNavigator } from '../navigation'

  const page = usePageNavigator()

  export let onKeyDown: ((e: KeyboardEvent) => null | boolean) | undefined = undefined

  function handleWindowKeyEvent(e: KeyboardEvent) {
    if (onKeyDown?.(e) !== false) {
      handleKeyboardEvent(e)
    }
  }
</script>

<svelte:window on:keydown={handleWindowKeyEvent} />

<slot />

// hify-client/src/navigable/headless/NavigablePage/NavigablePage.vue
<script setup lang="ts">
import { usePageNavigator } from '../../navigation'
import InternalNavWrapper from '../InternalNavWrapper.vue'

const page = usePageNavigator()
</script>

<svelte:window />

<template>
  <InternalNavWrapper :nav="page" :props="{}">
    <slot :page />
  </InternalNavWrapper>
</template>
