// hify-client/src/components/molecules/AlbumsRow/AlbumsRow.svelte
<script lang="ts">
import { ctxMenuCallbacks, ctxMenuOptions } from '@globals/context-menu-items'
import type { AlbumCardFragment } from '@graphql/generated'
import Card from '@molecules/Card/Card.svelte'
import ProgressiveRow from '@molecules/ProgressiveRow/ProgressiveRow.svelte'
import { ROUTES } from '@root/routes'
import { navigate } from 'svelte-navigator'

export let albums: AlbumCardFragment[]
</script>

<ProgressiveRow
  items={albums}
  idProp="id"
  onItemPress={(album) => navigate(ROUTES.album(album.id))}
  onItemLongPress={() => {
    // TODO: context menu
  }}
  let:item={album}
>
  <!-- TODO: enforceMaxWidth? -->
  <Card title={album.name} subtitle={album.albumArtists.map((artist) => artist.name).join(', ')} art={album.art} />
</ProgressiveRow>

// hify-client/src/components/molecules/AlbumsRow.vue
<script setup lang="ts">
import type { AlbumFragment } from '@/graphql/generated/graphql'
import Card from './Card.vue'
import ProgressiveRow from './ProgressiveRow.vue'
import router from '@/router';

defineProps<{
    albums: AlbumFragment[]
}>()
</script>

<template>
    <ProgressiveRow :items="albums" idProp="id"
        @item-press="(album) => router.push({ name: 'album', params: { id: album.id } })" v-slot="{ item: album }">
        <Card :title="album.name" :subtitle="album.albumArtists.map((artist) => artist.name).join(', ')"
            art-type="album" :art-item="album" />
    </ProgressiveRow>
</template>
