// hify-client/src/molecules/AlbumCard/AlbumCard.svelte
<script lang="ts">
  import { useNavigate } from 'svelte-navigator'
  import { AlbumInfos, ArtistInfos } from '../../graphql/generated'
  import { getAlbumArtUri } from '../../rest-api'
  import { ROUTES } from '../../routes'
  import Card from '../Card/Card.svelte'

  export let album: Pick<AlbumInfos, 'id' | 'name'> & {
    albumArtists: Array<Pick<ArtistInfos, 'name'>>
  }

  const navigate = useNavigate()
</script>

<Card
  title={album.name}
  subtitle={album.albumArtists.map((artist) => artist.name).join(', ')}
  onPress={() => navigate(ROUTES.album(album.id))}
  pictureUrl={getAlbumArtUri(album.id)}
/>

// hify-client/src/components/molecules/AlbumCard.vue
<script setup lang="ts">
import type { AlbumFragment } from '@/graphql/generated/graphql'
import SimpleNavigableItem from '@/navigable/headless/SimpleNavigableItem/SimpleNavigableItem.vue';
import router from '@/router';
import Card from './Card.vue';

defineProps<{
    album: AlbumFragment,
}>()
</script>

<template>
    <SimpleNavigableItem @press="router.push({ name: 'album', params: { id: album.id } })">
        <Card :title="album.name" :subtitle="album.albumArtists.map((artist) => artist.name).join(', ')"
            :art="album.art" />
    </SimpleNavigableItem>
</template>
