// hify-client/src/components/molecules/ArtistsRow/ArtistsRow.svelte
<script lang="ts">
import { ctxMenuCallbacks, ctxMenuOptions } from '@globals/context-menu-items'
import type { ArtistCardFragment } from '@graphql/generated'
import Card from '@molecules/Card/Card.svelte'
import ProgressiveRow from '@molecules/ProgressiveRow/ProgressiveRow.svelte'
import { showContextMenu } from '@navigable/ui/molecules/ContextMenu/ContextMenu'
import { ROUTES } from '@root/routes'
import { navigate } from 'svelte-navigator'

export let artists: ArtistCardFragment[]
</script>

<ProgressiveRow
  items={artists}
  idProp="id"
  onItemPress={(artist) => navigate(ROUTES.artist(artist.id))}
  onItemLongPress={(artist) => {
    showContextMenu(ctxMenuOptions.forArtist(artist.id))
  }}
  let:item={artist}
>
  <!-- TODO: enforceMaxWidth? -->
  <Card title={artist.name} subtitle="" art={artist.art} />
</ProgressiveRow>

// hify-client/src/components/molecules/ArtistsRow.vue
<script setup lang="ts">
import router from '@/router'
import { ctxMenuOptions } from '@/global/context-menu-items'
import type { ArtistFragment } from '@/graphql/generated/graphql'
import Card from '@/components/molecules/Card.vue'
import ProgressiveRow from '@/components/molecules/ProgressiveRow.vue'
import { showContextMenu } from '@/navigable/ui/molecules/ContextMenu/ContextMenu'

defineProps<{ artists: ArtistFragment[] }>()
</script>

<template>
    <ProgressiveRow :items="artists" idProp="id"
        @item-press="(artist) => router.push({ name: 'artist', params: { id: artist.id } })"
        @item-long-press="(artist) => showContextMenu(ctxMenuOptions.forArtist(artist.id))" v-slot="{ item: artist }">
        <Card :title="artist.name" :art="artist.art" />
    </ProgressiveRow>
</template>
