// hify-client/src/molecules/ArtistCard/ArtistCard.svelte
<script lang="ts">
  import { navigate } from 'svelte-navigator'
  import { ArtistCardFragment } from '../../graphql/generated'
  import { getArtistArtUri } from '../../rest-api'
  import { ROUTES } from '../../routes'
  import { bind } from '../../utils'
  import InteractiveCard from '../Card/InteractiveCard.svelte'

  export let artist: ArtistCardFragment
</script>

<InteractiveCard
  title={artist.name}
  subtitle=""
  onPress={bind(artist, (artist) => navigate(ROUTES.artist(artist.id)))}
  pictureUrl={getArtistArtUri(artist.id)}
  rounded={true}
/>

// hify-client/src/components/molecules/ArtistCard.tsx
import type { Artist } from '#/api/types.ts'
import { urls } from '#/api/urls.ts'
import { NavItem } from '#/components/navigables/Item.tsx'
import { navigate } from '#/router/routes.ts'
import { routes } from '#/routes.ts'
import { Card } from './Card'

export type ArtistCardProps = {
  artist: Artist
}

export function ArtistCard({ artist }: ArtistCardProps) {
  return (
    <NavItem onPress={() => navigate(routes.artist, { artistId: artist.id })}>
      <Card
        className="p-2 [&_img]:rounded-full"
        title={artist.name}
        artUrl={urls.artistArt(artist, 'small')}
      />
    </NavItem>
  )
}
