// hify-client/src/components/molecules/ArtistCard/ArtistCard.svelte
<script lang="ts">
  import { navigate } from 'svelte-navigator'
  import { ArtistCardFragment, MixOrdering } from '@graphql/generated'
  import { ROUTES } from '@root/routes'
  import { bind } from '@globals/utils'
  import InteractiveCard from '../Card/InteractiveCard.svelte'
  import { ContextMenuOption, showContextMenu } from '@navigable/ui/molecules/ContextMenu/ContextMenu'
  import { MIN_GREAT_RATING } from '@root/constants'
  import { generateAndPlayMix } from '../../../stores/play-queue'

  export let artist: ArtistCardFragment

  $: contextMenuOptions = [
    {
      label: 'Mix me some magic ✨',
      onPress: bind(
        artist.id,
        (id) =>
          void generateAndPlayMix({
            source: { allTracks: '-' },
            ordering: MixOrdering.Random,
            minRating: MIN_GREAT_RATING,
            fromArtists: [id],
          }),
      ),
    },
  ] satisfies ContextMenuOption[]
</script>

<InteractiveCard
  title={artist.name}
  subtitle=""
  onPress={bind(artist, (artist) => navigate(ROUTES.artist(artist.id)))}
  onLongPress={() => showContextMenu(contextMenuOptions)}
  art={artist.art}
  circle={true}
/>

// hify-client/src/components/molecules/ArtistCard.vue
<script setup lang="ts">
import { type ArtFragment, MixOrdering, type ArtistFragment, ArtFragmentDoc } from '@/graphql/generated/graphql'
import { type ContextMenuOption, showContextMenu } from '@/navigable/ui/molecules/ContextMenu/ContextMenu'
import { MIN_GREAT_RATING } from '@/global/constants'
import { generateAndPlayMix } from '@/global/stores/play-queue'
import { computed } from 'vue'
import router from '@/router'
import SimpleNavigableItem from '@/navigable/headless/SimpleNavigableItem/SimpleNavigableItem.vue'
import Card from './Card.vue'

const { artist } = defineProps<{
    artist: ArtistFragment
}>()

const contextMenuOptions = computed<ContextMenuOption[]>(() => [
    {
        label: 'Mix me some magic ✨',
        onPress() {
            generateAndPlayMix({
                source: { allTracks: '-' },
                ordering: MixOrdering.Random,
                minRating: MIN_GREAT_RATING,
                fromArtists: [artist.id]
            })
        }
    }

])
</script>

<template>
    <SimpleNavigableItem @press="router.push({ name: 'artist', params: { id: artist.id } })"
        @long-press="showContextMenu(contextMenuOptions)">
        <Card :title="artist.name" :art="artist.art" circle />
    </SimpleNavigableItem>
</template>
