// hify-client/src/molecules/Card/Card.svelte
<script lang="ts">
  import ImgLoader from '../../atoms/ImgLoader/ImgLoader.svelte'
  import { ProgressiveImgFragment } from '../../graphql/generated'

  export let art: ProgressiveImgFragment | null | undefined

  export let title: string
  export let subtitle: string | null = null

  export let boxSize = 120
  export let circle = false

  // 'enforceMaxWidth' is useful for situations like rows where the card may try to take more width than they should
  // It is harmful though in other contexts like set grids where the width is fixed and cannot be changed
  export let enforceMaxWidth = false
</script>

<div class="card" class:enforceMaxWidth style="--width: {boxSize}px">
  <ImgLoader {art} let:src>
    <img class="cover" class:circle width={boxSize} height={boxSize} {src} alt="" />
  </ImgLoader>

  <div class="title experimental-line-limiter">{title}</div>

  {#if subtitle}
    <div class="subtitle experimental-line-limiter">{subtitle}</div>
  {/if}
</div>

<style>
  .card {
    text-align: center;
    transition: transform 0.25s;
  }

  .card.enforceMaxWidth {
    max-width: var(--width);
  }

  .cover.circle {
    border-radius: 50%;
  }

  /* .card.focused {
    transition: transform 0.25s;
    transform: scale(1.33);
    text-decoration: none !important;
    z-index: 2;
  } */

  /* .title {
    font-weight: bold;
  } */

  .subtitle {
    font-size: 0.9rem;
    /* font-style: italic; */
  }

  /* TODO: remove experimental stuff */
  .experimental-line-limiter {
    overflow: hidden;
    text-overflow: ellipsis;
    display: -webkit-box;
    -webkit-line-clamp: 2;
    line-clamp: 2;
    -webkit-box-orient: vertical;
  }
</style>

// hify-client/src/components/molecules/Card.vue
<script setup lang="ts">
import ImgLoader from '../atoms/ImgLoader.vue'
import type { ArtFragment } from '@/graphql/generated/graphql'

defineProps<{
    art: ArtFragment | null | undefined,
    title: string,

    subtitle?: string,
    boxSize?: number,
    circle?: boolean,
    opacity?: number,

    // 'enforceMaxWidth' is useful for situations like rows where the card may try to take more width than they should
    // It is harmful though in other contexts like set grids where the width is fixed and cannot be changed
    enforceMaxWidth?: boolean
}>()
</script>

<template>
    <div class="card" :class="{ enforceMaxWidth }" :style="`--width: ${boxSize ?? 120}px; --opacity: ${opacity ?? 1};`">
        <ImgLoader :art v-slot="{ src }">
            <img class="cover" :class="{ circle }" :width="boxSize ?? 120" :height="boxSize ?? 120" :src alt="" />
        </ImgLoader>

        <div class="title experimental-line-limiter">{{ title }}</div>

        <div v-if="subtitle" class="subtitle experimental-line-limiter">{{ subtitle }}</div>
    </div>

</template>

<style scoped>
.card {
    text-align: center;
    transition: transform 0.25s;
    opacity: var(--opacity);
}

.card.enforceMaxWidth {
    max-width: var(--width);
}

.cover.circle {
    border-radius: 50%;
}

/* .card.focused {
    transition: transform 0.25s;
    transform: scale(1.33);
    text-decoration: none !important;
    z-index: 2;
  } */

/* .title {
    font-weight: bold;
  } */

.subtitle {
    font-size: 0.9rem;
    /* font-style: italic; */
}

/* TODO: remove experimental stuff */
.experimental-line-limiter {
    overflow: hidden;
    text-overflow: ellipsis;
    display: -webkit-box;
    -webkit-line-clamp: 2;
    line-clamp: 2;
    -webkit-box-orient: vertical;
}
</style>
