// hify-client/src/components/molecules/Card/InteractiveCard.svelte
<script lang="ts">
import { ProgressiveImgFragment } from '@graphql/generated'
import SimpleNavigableItem from '@navigable/headless/SimpleNavigableItem/SimpleNavigableItem.svelte'
import Card from './Card.svelte'
import { SimpleNavigableItemProps } from '@navigable/headless/SimpleNavigableItem/SimpleNavigableItem'

export let art: ProgressiveImgFragment | null | undefined

export let title: string
export let subtitle: string | null = null

export let onPress: NonNullable<SimpleNavigableItemProps['onPress']>
export let onLongPress: SimpleNavigableItemProps['onLongPress'] = undefined
export let onFocus: SimpleNavigableItemProps['onFocus'] = undefined

export let enforceMaxWidth: boolean | undefined = undefined
export let circle: boolean | undefined = undefined
</script>

<SimpleNavigableItem {onPress} {onLongPress} {onFocus}>
  <Card {art} {title} {subtitle} {enforceMaxWidth} {circle} />
</SimpleNavigableItem>

// hify-client/src/components/molecules/InteractiveCard.vue
<script setup lang="ts">
import type { ArtFragment } from '@/graphql/generated/graphql'
import type { SimpleNavigableItemProps } from '@/navigable/headless/SimpleNavigableItem/SimpleNavigableItem.vue'
import SimpleNavigableItem from '@/navigable/headless/SimpleNavigableItem/SimpleNavigableItem.vue';
import Card from './Card.vue';

// TODO: inherit some props from 'Card' and from 'SimpleNavigableItem'
defineProps<{
    art: ArtFragment | null | undefined,
    title: string,

    subtitle?: string,
    onPress: SimpleNavigableItemProps['onPress'],

    onLongPress?: SimpleNavigableItemProps['onLongPress'],
    onFocus?: SimpleNavigableItemProps['onFocus'],

    enforceMaxWidth?: boolean,
    circle?: boolean
}>()
</script>

<template>
    <SimpleNavigableItem :on-press :on-long-press :on-focus>
        <Card :art :title :subtitle :enforce-max-width :circle />
    </SimpleNavigableItem>
</template>
