// hify-client/src/navigable/headless/NavigableGrid/NavigableGrid.vue
<script setup lang="ts">
import { getParentNavigable } from '@/navigable/navigation';
import { NavigableGrid, type NavigableGridProps } from './NavigableGrid';
import InternalNavWrapper from '../InternalNavWrapper.vue';

const props = defineProps<NavigableGridProps>()

const grid = new NavigableGrid(getParentNavigable(), props)

defineSlots<{
    default(props: { grid: NavigableGrid }): unknown
}>()
</script>

<template>
    <InternalNavWrapper :nav="grid" :props>
        <slot :grid />
    </InternalNavWrapper>
</template>

// hify-client/src/navigable/headless/NavigableGrid/NavigableGrid.svelte
<script lang="ts">
  import { afterUpdate } from 'svelte'
  import InternalNavWrapper from '../InternalNavWrapper.svelte'

  import { getParentNavigable, Props, setChildrenNavigable } from '../../navigation'
  import { NavigableGrid } from './NavigableGrid'

  export let hasFocusPriority: Props<NavigableGrid>['hasFocusPriority'] = null

  export let columns: Props<NavigableGrid>['columns']
  export let lazyLoader: Props<NavigableGrid>['lazyLoader'] = undefined

  const gridProps = (): Props<NavigableGrid> => ({
    hasFocusPriority,
    columns,
    lazyLoader,
  })

  const grid = new NavigableGrid(getParentNavigable(), gridProps())

  setChildrenNavigable(grid)

  afterUpdate(() => grid.updateProps(gridProps()))

  export const requestFocus = () => grid.requestFocus()
</script>

<InternalNavWrapper navId={grid.id}>
  <slot nav={grid} />
</InternalNavWrapper>
