// hify-client/src/components/atoms/Input/Input.svelte
<script lang="ts">
  import SimpleNavigableItem from '@navigable/headless/SimpleNavigableItem/SimpleNavigableItem.svelte'
  import { RequestFocus } from '@navigable/navigation'

  let searchField: HTMLInputElement

  export let requestFocus: RequestFocus

  export let value: string
</script>

<SimpleNavigableItem
  bind:requestFocus
  onFocus={() => searchField.focus()}
  onUnfocus={() => searchField.blur()}
  display="transparent"
  noPadding
  notRounded
>
  <input type="text" bind:this={searchField} bind:value />
</SimpleNavigableItem>

// hify-client/src/components/atoms/Input.vue
<script setup lang="ts">
import SimpleNavigableItem from '@/navigable/headless/SimpleNavigableItem/SimpleNavigableItem.vue'
import { ref } from 'vue';

const props = defineProps<{ value: string }>()

const value = ref(props.value)

defineExpose({ value })

const searchFieldRef = ref<HTMLInputElement | null>(null)
</script>

<template>
    <SimpleNavigableItem class="contents" @focus="searchFieldRef?.focus()" @unfocus="searchFieldRef?.blur()">
        <input type="text" ref="searchField" v-model="value" />
    </SimpleNavigableItem>
</template>
