// hify-client/src/atoms/NavigableTrack/NavigableTrack.svelte
<script lang="ts">
  import { navigate } from 'svelte-navigator'
  import { AudioTrackFragment } from '../../graphql/generated'
  import { showContextMenu } from '../../navigable/ui/molecules/ContextMenu/ContextMenu'

  import SimpleNavigableItem from '../../navigable/headless/SimpleNavigableItem/SimpleNavigableItem.svelte'
  import { ItemDisplay } from '../../navigable/headless/SimpleNavigableItem/SimpleNavigableItem.svelte'
  import { ROUTES } from '../../routes'
  import { playTrackFromNewQueue, queueAsNext } from '../../stores/play-queue'

  export let tracks: AudioTrackFragment[]
  export let track: AudioTrackFragment
  export let goToAlbumOption = true
  export let display: ItemDisplay = null

  function play() {
    playTrackFromNewQueue(tracks, tracks.indexOf(track))
    navigate(ROUTES.nowPlaying)
  }
</script>

<SimpleNavigableItem
  let:item
  let:focused
  onPress={play}
  onLongPress={() =>
    showContextMenu(
      (goToAlbumOption
        ? [{ label: 'Go to album', onPress: () => navigate(ROUTES.album(track.metadata.tags.album.id)) }]
        : []
      ).concat([
        { label: 'Play next', onPress: () => queueAsNext([track]) },
        { label: 'Play alone', onPress: () => playTrackFromNewQueue([track], 0) },
      ])
    )}
  {display}
  fullHeight
>
  <slot {item} {focused} />
</SimpleNavigableItem>

// hify-client/src/components/atoms/NavigableTrack.vue
<script setup lang="ts">
import { ctxMenuCallbacks, ctxMenuOptions, type TrackContext } from '@/global/context-menu-items';
import type { AudioTrackFragment } from '@/graphql/generated/graphql';
import type { SimpleNavigableItem as SimpleNavigableItemClass } from '@/navigable/headless/SimpleNavigableItem/SimpleNavigableItem';
import type { SimpleNavigableItemProps } from '@/navigable/headless/SimpleNavigableItem/SimpleNavigableItem.vue'
import SimpleNavigableItem from '@/navigable/headless/SimpleNavigableItem/SimpleNavigableItem.vue';
import { showContextMenu } from '@/navigable/ui/molecules/ContextMenu/ContextMenu';

const { fromMixId = null } = defineProps<{
    track: AudioTrackFragment,
    tracks: AudioTrackFragment[],
    context: TrackContext,
    fromMixId?: string,
    onFocus?: SimpleNavigableItemProps['onFocus']
}>()

defineSlots<{
    default(props: {
        item: SimpleNavigableItemClass,
        focused: boolean
    }): unknown
}>()
</script>

<template>
    <SimpleNavigableItem v-slot="{ item, focused }" @press="ctxMenuCallbacks.playTrack(track, tracks, fromMixId)"
        @long-press="showContextMenu(ctxMenuOptions.forTrack(track, { fromMixId }, context))" @focus="onFocus">
        <slot :item :focused />
    </SimpleNavigableItem>
</template>
