// hify-client/src/components/atoms/NavigableTrack/NavigableTrack.svelte
<script context="module" lang="ts">
</script>

<script lang="ts">
  import { AudioTrackFragment } from '@graphql/generated'
  import { showContextMenu } from '@navigable/ui/molecules/ContextMenu/ContextMenu'

  import SimpleNavigableItem from '@navigable/headless/SimpleNavigableItem/SimpleNavigableItem.svelte'
  import { ItemDisplay } from '@navigable/headless/SimpleNavigableItem/SimpleNavigableItem.svelte'
  import { SimpleNavigableItemProps } from '@navigable/headless/SimpleNavigableItem/SimpleNavigableItem'
  import { TrackContext, ctxMenuCallbacks, ctxMenuOptions } from '@globals/context-menu-items'

  export let tracks: AudioTrackFragment[]
  export let track: AudioTrackFragment
  export let context: TrackContext
  export let display: ItemDisplay = null
  export let fromMixId: string | null = null
  export let onFocus: SimpleNavigableItemProps['onFocus'] = undefined
</script>

<SimpleNavigableItem
  let:item
  let:focused
  onPress={() => ctxMenuCallbacks.playTrack(track, tracks, fromMixId)}
  onLongPress={() => showContextMenu(ctxMenuOptions.forTrack(track, { fromMixId }, context))}
  fullHeight
  {display}
  {onFocus}
>
  <slot {item} {focused} />
</SimpleNavigableItem>

// hify-client/src/components/atoms/NavigableTrack.vue
<script setup lang="ts">
import { ctxMenuCallbacks, ctxMenuOptions, type TrackContext } from '@/global/context-menu-items';
import type { AudioTrackFragment } from '@/graphql/generated/graphql';
import type { SimpleNavigableItem as SimpleNavigableItemClass } from '@/navigable/headless/SimpleNavigableItem/SimpleNavigableItem';
import type { SimpleNavigableItemProps } from '@/navigable/headless/SimpleNavigableItem/SimpleNavigableItem.vue'
import SimpleNavigableItem from '@/navigable/headless/SimpleNavigableItem/SimpleNavigableItem.vue';
import { showContextMenu } from '@/navigable/ui/molecules/ContextMenu/ContextMenu';

const { fromMixId = null } = defineProps<{
    track: AudioTrackFragment,
    tracks: AudioTrackFragment[],
    context: TrackContext,
    fromMixId?: string,
    onFocus?: SimpleNavigableItemProps['onFocus']
}>()

defineSlots<{
    default(props: {
        item: SimpleNavigableItemClass,
        focused: boolean
    }): unknown
}>()
</script>

<template>
    <SimpleNavigableItem v-slot="{ item, focused }" @press="ctxMenuCallbacks.playTrack(track, tracks, fromMixId)"
        @long-press="showContextMenu(ctxMenuOptions.forTrack(track, { fromMixId }, context))" @focus="onFocus">
        <slot :item :focused />
    </SimpleNavigableItem>
</template>
